### ISSUE TITLE
Broken site title link 

### ISSUE THREAD

**Issue by stebrech** [WPZOO/penguin-gold#39]
https://twitter.com/Ruby/status/960993004138958848

**Comment by rubyji** [comment]
Thanks for creating this issue. As I tweeted: I updated, and now the site title in the navbar links to the page the viewer is already on instead of to the home page. 

You can see this live at http://lotusmedia.org/.  Click on a post, then hover over "RUBY SINREICH" the title in the navba and you will see it is a link to the page you are on instead of to the home page as it used to be and should be.

**Comment by stebrech** [comment]
Fixed in 2976c33
